CREATE DATABASE BACKEND;
USE BACKEND;

CREATE TABLE USERS (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isThirdParty BOOLEAN NOT NULL DEFAULT FALSE,
    thirdPartyProvider VARCHAR(255),
    thrirdPartyRefreshToken VARCHAR(255),
    thirdPartyId VARCHAR(255)
);
